lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('__debug__/', include('debug_toolbar.urls')),

    path('students/', include('students.urls')),

    path('groups/', include('groups.urls')),

    path('teachers/', include('teachers.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

# https://docs.djangoproject.com:8000/en/4.1/topics/http/urls/

teachers/urls.py
from django.urls import path

from .views import CreateTeacherView
from .views import DeleteTeacherView
from .views import DetailTeacherView
from .views import ListTeacherView
from .views import UpdateTeacherView


app_name = 'teachers'

urlpatterns = [
    path('', ListTeacherView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('detail/<int:pk>/', DetailTeacherView.as_view(), name='detail'),
    path('update/<int:pk>/', UpdateTeacherView.as_view(), name='update'),
    path('delete/<int:pk>/', DeleteTeacherView.as_view(), name='delete'),
]

teachers/models.py
from random import randint

from core.models import PersonModel

from django.db import models


class Teacher(PersonModel):
    salary = models.PositiveIntegerField(default=10_000)

    def __str__(self):
        return f'{self.first_name} {self.last_name} (${self.salary})'

    class Meta:
        db_table = 'teachers'

    @classmethod
    def _generate(cls):
        obj = super()._generate()
        obj.salary = randint(10_000, 100_000)
        obj.save()

teachers/forms.py
from django import forms

from django_filters import FilterSet

from .models import Teacher


class BaseTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
          # '__all__',
          'first_name',
          'last_name',
          'birthday',
          'email',
          'phone_number',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

    # def clean(self):

    def clean_birthday(self):
        value = self.cleaned_data.get('birthday')

        return value

    def clean_first_name(self):
        return self.cleaned_data['first_name'].title()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].title()

    def clean_phone_number(self):
        value = self.cleaned_data['phone_number']
        return "".join(char for char in value if char in "0123456789-()")


class CreateTeacherForm(BaseTeacherForm):
    pass


class UpdateTeacherForm(BaseTeacherForm):
    class Meta(BaseTeacherForm.Meta):
        fields = [
            # '__all__',
            'first_name',
            'last_name',
            'birthday',
            'phone_number',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }


class TeacherFilterForm(FilterSet):
    class Meta:
        model = Teacher
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith'],
        }

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import CreateTeacherForm, TeacherFilterForm, UpdateTeacherForm
from .models import Teacher


class ListTeacherView(ListView):
    model = Teacher
    template_name = 'teachers/list.html'

    def get_queryset(self):
        teachers = Teacher.objects.all()
        filter_form = TeacherFilterForm(data=self.request.GET, queryset=teachers)

        return filter_form


class CreateTeacherView(LoginRequiredMixin, CreateView):
    model = Teacher
    template_name = 'teachers/create.html'
    success_url = reverse_lazy('teachers:list')
    form_class = CreateTeacherForm


class DetailTeacherView(LoginRequiredMixin, DetailView):
    model = Teacher
    template_name = 'teachers/detail.html'


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    model = Teacher
    template_name = 'teachers/update.html'
    success_url = reverse_lazy('teachers:list')
    form_class = UpdateTeacherForm


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    template_name = 'teachers/delete.html'
    success_url = reverse_lazy('teachers:list')

teachers/templates/teachers/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create new teacher{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-outline-success mt-3 btn-sm" type="submit" value="Create">
                    <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'teachers:list' %}">Cancel</a>
                </form>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

teachers/templates/teachers/delete.html
{% extends 'base.html' %}

{% block title %}Delete teacher{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove "{{ teacher.last_name }} {{ teacher.first_name }}"?</p>
        <input class="btn btn-outline-danger mt-3 btn-sm" type="submit" value="Agree">
        <a class="btn btn-outline-success mt-3 btn-sm" href="{% url 'teachers:list' %}">Cancel</a>
    </form>
{% endblock %}

teachers/templates/teachers/detail.html
{% extends 'base.html' %}

{% block title %}Detail of {{ teacher.first_name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4"></div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <a href="{% url 'teachers:update' teacher.pk %}">{{ teacher.first_name }} {{ teacher.last_name }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {{ teacher.birthday }}{% if teacher.get_age %}
                            <span class="text-muted">({{ teacher.get_age }} years)</span>
                        {% endif %}
                    </li>
                    <li class="list-group-item">{{ teacher.email }}</li>
                    <li class="list-group-item">{{ teacher.phone_number }}</li>
                </ul>
                <a class="btn btn-outline-primary mt-3" href="{% url 'teachers:list' %}">Back to list</a>
            </div>
        </div>
    <div class="col-4"></div>
    </div>
{% endblock %}

teachers/templates/teachers/list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}List of teachers{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Search teacher
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="col">
                            <form method="get">
                                {{ object_list.form|crispy }}
                                <input class="btn btn-outline-primary mt-3" type="submit" value="Search">
                            </form>
                        </div>
                        <div class="col-6"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
            <tr align="center">
                <th>N</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Age</th>
                {% if user.is_authenticated %}
                <th><i class="bi bi-pencil-fill"></i></th>
                <th><i class="bi bi-trash-fill"></i></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for teacher in object_list.qs %}
                <tr align="center">
                    <td>{{ forloop.counter }}</td>
                    <td>
                        {% if user.is_authenticated %}
                            <a href="{% url 'teachers:detail' teacher.pk %}">{{ teacher.first_name }}</a>
                        {% else %}
                            {{ teacher.first_name }}
                        {% endif %}
                    </td>
                    <td>{{ teacher.last_name }}</td>
                    <td>{% if teacher.get_age %}{{ teacher.get_age }}{% endif %}</td>
                    {% if user.is_authenticated %}
                        <td><a class="btn btn-outline-primary btn-sm"
                               href="{% url 'teachers:update' teacher.pk %}">Edit</a></td>
                        <td><a class="btn btn-outline-danger btn-sm" href="{% url 'teachers:delete' teacher.pk %}">Delete</a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

teachers/templates/teachers/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update teacher{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-outline-success mt-3 btn-sm" type="submit" value="Update">
                    <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'teachers:list' %}">Cancel</a>
                </form>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}