accounts/urls.py
from django.urls import path

from .views import AccountLoginView, AccountLogoutView, AccountRegisterView, account_view, AccountUpdateView

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountRegisterView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_view, name='profile_view'),
    path('update/', AccountUpdateView.as_view(), name='profile_update'),
]

lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('__debug__/', include('debug_toolbar.urls')),

    path('students/', include('students.urls')),

    path('groups/', include('groups.urls')),

    path('teachers/', include('teachers.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

# https://docs.djangoproject.com:8000/en/4.1/topics/http/urls/

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        db_table = 'profiles'


@receiver(post_save, sender=User)
def create_new_profile(sender, instance, created, **kwargs):
    if created:
        p = Profile(user=instance)
        p.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import Profile


class UserRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm.Meta):
        fields = [
            'first_name',
            'last_name',
            'email',
        ]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'birthday',
            'city',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.edit import ProcessFormView

from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


class AccountRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/register.html'


class AccountLoginView(LoginView):
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'User <{self.request.user}> has successfully logged in.')
        # messages.error(self.request, f'User <{self.request.user}> has successfully logged in.')
        # messages.warning(self.request, f'User <{self.request.user}> has successfully logged in.')
        # messages.info(self.request, f'User <{self.request.user}> has successfully logged in.')
        return response


class AccountLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/logout.html'


@login_required
def account_view(request):
    return render(request, 'accounts/profile_view.html')


class AccountUpdateView(LoginRequiredMixin, ProcessFormView):
    def get(self, request, *args, **kwargs):
        user = request.user
        profile = user.profile
        user_form = UserUpdateForm(instance=user)
        profile_form = ProfileUpdateForm(instance=profile)

        return render(request, 'accounts/update.html', {'user_form': user_form, 'profile_form': profile_form})

    def post(self, request, *args, **kwargs):
        user = request.user
        profile = user.profile
        user_form = UserUpdateForm(instance=user, data=request.POST)
        profile_form = ProfileUpdateForm(instance=profile, data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('accounts:profile_view'))

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Login user{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <a href="{% url 'password_reset' %}">If you forgot password, click me!</a>
                    <div class="mt-3 text-center">
                        <input class="btn btn-outline-success mt-3 btn-sm" type="submit" value="Login">
                        <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'accounts:register' %}">Register</a>
                    </div>
                </form>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Logout user{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col text-center">
                <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'home' %}">Home</a>
                <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'accounts:login' %}">Login</a>
                <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'accounts:register' %}">Register</a>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_view.html
{% extends 'base.html' %}

{% block title %}User profile{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <div class="p-3 m-3">
                <h2 class="account-heading">{{ user.last_name }} {{ user.first_name }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><span class="h5">Username: </span>{{ user.username }}</li>
                <li class="list-group-item">
                    <span class="h5">Birthday: </span>
                    {% if user.profile.birthday %}
                        {{ user.profile.birthday }}
                    {% endif %}
                </li>
                <li class="list-group-item">
                    <span class="h5">City: </span>
                    {% if user.profile.city %}
                        {{ user.profile.city }}
                    {% endif %}
                </li>
            </ul>
            <div class="mt-3 text-center">
                <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'accounts:profile_update' %}">Change profile</a>
                <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'password_change' %}">Change password</a>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create user{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="mt-3 text-center">
                        <input class="btn btn-outline-success mt-3 btn-sm" type="submit" value="Register">
                        <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'accounts:login' %}">Login</a>
                    </div>
                </form>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update profile{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ user_form|crispy }}
                    {{ profile_form|crispy }}
                    <div class="mt-3 text-center">
                        <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'accounts:profile_view' %}">Back</a>
                        <input class="btn btn-outline-success mt-3 btn-sm" type="submit" value="Update">
                    </div>
                </form>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}