accounts/urls.py
from django.urls import path

from .views import AccountLoginView, AccountLogoutView, AccountRegisterView, account_view, AccountUpdateView

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountRegisterView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_view, name='profile_view'),
    path('update/', AccountUpdateView.as_view(), name='profile_update'),
]

courses/urls.py
from django.urls import path

from .views import CreateCourseView
from .views import DeleteCourseView
from .views import DetailCourseView
from .views import ListCourseView
from .views import UpdateCourseView

app_name = 'courses'

urlpatterns = [
    path('', ListCourseView.as_view(), name='list'),
    path('create/', CreateCourseView.as_view(), name='create'),
    path('detail/<int:pk>/', DetailCourseView.as_view(), name='detail'),
    path('update/<int:pk>/', UpdateCourseView.as_view(), name='update'),
    path('delete/<int:pk>/', DeleteCourseView.as_view(), name='delete'),
]

groups/urls.py
from django.urls import path

from .views import CreateGroupView
from .views import DeleteGroupView
from .views import DetailGroupView
from .views import ListGroupView
from .views import UpdateGroupView

app_name = 'groups'

urlpatterns = [
    path('', ListGroupView.as_view(), name='list'),
    path('create/', CreateGroupView.as_view(), name='create'),
    path('detail/<int:pk>/', DetailGroupView.as_view(), name='detail'),
    path('update/<int:pk>/', UpdateGroupView.as_view(), name='update'),
    path('delete/<int:pk>/', DeleteGroupView.as_view(), name='delete'),
]

lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('__debug__/', include('debug_toolbar.urls')),

    path('students/', include('students.urls')),

    path('groups/', include('groups.urls')),

    path('teachers/', include('teachers.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

# https://docs.djangoproject.com:8000/en/4.1/topics/http/urls/

students/urls.py
from django.urls import path

from .views import (CreateStudentView, DeleteStudentView, DetailStudentView, ListStudentView, UpdateStudentView)

# from .views import CustomUpdateStudentView

app_name = 'students'

urlpatterns = [
    path('', ListStudentView.as_view(), name='list'),
    path('create/', CreateStudentView.as_view(), name='create'),
    path('detail/<int:pk>/', DetailStudentView.as_view(), name='detail'),
    # path('update/<int:pk>/', CustomUpdateStudentView.update, name='update'),
    path('update/<int:pk>/', UpdateStudentView.as_view(), name='update'),
    path('delete/<int:pk>/', DeleteStudentView.as_view(), name='delete'),
]

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %} danger{% else %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top bg-light" style="background-color: #e3f2fd;">
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'img/lms_logo.png' %}" alt="LMS" width="30" height="24">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Student
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'students:create' %}">Create</a></li>
                            <li><a class="dropdown-item" href="{% url 'students:list' %}">List</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'students:list' %}">List</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Groups
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'groups:create' %}">Create</a></li>
                            <li><a class="dropdown-item" href="{% url 'groups:list' %}">List</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'groups:list' %}">List</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Teachers
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'teachers:create' %}">Create</a></li>
                            <li><a class="dropdown-item" href="{% url 'teachers:list' %}">List</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'teachers:list' %}">List</a></li>
                        {% endif %}
                    </ul>
                </li>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Courses
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'courses:create' %}">Create</a></li>
                            <li><a class="dropdown-item" href="{% url 'courses:list' %}">List</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'courses:list' %}">List</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            {#      <form class="d-flex" role="search">#}
            {#        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">#}
            {#        <button class="btn btn-outline-success" type="submit">Search</button>#}
            {#      </form>#}
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Account
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'accounts:profile_view' %}">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/includes/paginator.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1{{ params }}"><i class="bi bi-chevron-double-left"></i></a>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ params }}"><i
                    class="bi bi-chevron-left"></i></a>
                {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-left"></i></a>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-left"></i></a>
            </li>
        {% endif %}

        {#        {% for page_num in page_obj.paginator.page_range %}#}
        {#        <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>#}
        {#        {% endfor %}#}

        {#        {% for page_num in page_obj.paginator.page_range %}#}
        {#            {% if page_num == page_obj.number %}#}
        {#                <li class="page-item active"><a class="page-link">{{ page_num }}</a></li>#}
        {#            {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}#}
        {#                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>#}
        {#            {% endif %}#}
        {#        {% endfor %}#}

        {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
                <li class="page-item active"><a class="page-link">{{ page_num }}</a></li>
            {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}{{ params }}">{{ page_num }}</a></li>

            {% elif page_obj.number == 1 and page_num < page_obj.number|add:5 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}{{ params }}">{{ page_num }}</a></li>
            {% elif page_obj.number == 2 and page_num < page_obj.number|add:4 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}{{ params }}">{{ page_num }}</a></li>
            {% elif page_obj.number == page_obj.paginator.num_pages and page_num > page_obj.number|add:-5 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}{{ params }}">{{ page_num }}</a></li>
            {% elif page_obj.number == page_obj.paginator.num_pages|add:-1 and page_num > page_obj.number|add:-4 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}{{ params }}">{{ page_num }}</a></li>

            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ params }}"><i
                    class="bi bi-chevron-right"></i></a>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{{ params }}"><i
                    class="bi bi-chevron-double-right"></i></a>
                {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-right"></i></a>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-right"></i></a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/includes/students_tab.html
<table class="table table-striped table-hover">
    <thead>
    <tr align="center">
        <th style="width: 55px;">N</th>
        <th>First name</th>
        <th>Last name</th>
        <th style="width: 55px;">Age</th>
        <th style="width: 55px;">Headman</th>
        {% if group_on %}
            <th style="width: 150px;">Group</th>
            {% if user.is_authenticated %}
                <th style="width: 85px;"><i class="bi bi-pencil-fill"></i></th>
                <th style="width: 85px;"><i class="bi bi-trash-fill"></i></th>
            {% endif %}
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for student in objects_list %}
        <tr align="center">
            <td>{% if is_paginated %}
                {{ forloop.counter0|add:page_obj.start_index }}
            {% else %}
                {{ forloop.counter }}
            {% endif %}</td>
            <td align="left">
                {% if user.is_authenticated %}
                    <a href="{% url 'students:detail' student.pk %}">{{ student.first_name }}</a>
                {% else %}
                    {{ student.first_name }}
                {% endif %}
            </td>
            <td align="left">{{ student.last_name }}</td>
            <td>{% if student.get_age %}{{ student.get_age }}{% endif %}</td>
            <td align="center">
                {% if student__headman_group %}<i class="bi bi-check2-circle"></i>{% endif %}
            </td>
            {% if group_on %}
                <td>{{ student.group.group_name }}</td>
                {% if user.is_authenticated %}
                    <td><a class="btn btn-outline-primary btn-sm" href="{% url 'students:update' student.pk %}">Edit</a>
                    </td>
                    <td><a class="btn btn-outline-danger btn-sm"
                           href="{% url 'students:delete' student.pk %}">Delete</a></td>
                {% endif %}
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>