courses/urls.py
from django.urls import path

from .views import CreateCourseView
from .views import DeleteCourseView
from .views import DetailCourseView
from .views import ListCourseView
from .views import UpdateCourseView

app_name = 'courses'

urlpatterns = [
    path('', ListCourseView.as_view(), name='list'),
    path('create/', CreateCourseView.as_view(), name='create'),
    path('detail/<int:pk>/', DetailCourseView.as_view(), name='detail'),
    path('update/<int:pk>/', UpdateCourseView.as_view(), name='update'),
    path('delete/<int:pk>/', DeleteCourseView.as_view(), name='delete'),
]

lms/urls.py
from core.views import index

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('__debug__/', include('debug_toolbar.urls')),

    path('students/', include('students.urls')),

    path('groups/', include('groups.urls')),

    path('teachers/', include('teachers.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
]

# https://docs.djangoproject.com:8000/en/4.1/topics/http/urls/

courses/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class Course(models.Model):
    course_name = models.CharField(
        max_length=100,
        verbose_name='course_name',
        db_column='course_name',
        validators=[MinLengthValidator(2, '"first_name" field less than two symbols')]
    )
    duration = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    group = models.OneToOneField(
        'groups.Group',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='course_group'
    )

    class Meta:
        db_table = 'courses'

    def __str__(self):
        return f"{self.course_name}"

courses/forms.py
from django import forms

from django_filters import FilterSet

from .models import Course


class CourseBaseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class CreateCourseForm(CourseBaseForm):
    pass


class UpdateCourseForm(CourseBaseForm):
    pass


class CourseFilterForm(FilterSet):
    class Meta:
        model = Course
        fields = {
            'course_name': ['exact', 'icontains'],
        }

courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from .forms import CourseFilterForm, CreateCourseForm, UpdateCourseForm
from .models import Course


class ListCourseView(ListView):
    model = Course
    template_name = 'courses/list.html'

    def get_queryset(self):
        courses = Course.objects.all()
        filter_form = CourseFilterForm(data=self.request.GET, queryset=courses)

        return filter_form


class CreateCourseView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = 'courses/create.html'
    success_url = reverse_lazy('courses:list')
    form_class = CreateCourseForm


class DetailCourseView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'courses/detail.html'


class UpdateCourseView(LoginRequiredMixin, UpdateView):
    model = Course
    template_name = 'courses/update.html'
    form_class = UpdateCourseForm
    success_url = reverse_lazy('courses:list')


class DeleteCourseView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = 'courses/delete.html'
    success_url = reverse_lazy('courses:list')

courses/templates/courses/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create new course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-outline-success mt-3 btn-sm" type="submit" value="Create">
                    <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'courses:list' %}">Cancel</a>
                </form>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/delete.html
{% extends 'base.html' %}

{% block title %}Delete course{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to remove course: "{{ course.course_name }}"?</p>
        <input class="btn btn-outline-danger mt-3 btn-sm" type="submit" value="Agree">
        <a class="btn btn-outline-success mt-3 btn-sm" href="{% url 'courses:list' %}">Cancel</a>
    </form>
{% endblock %}

courses/templates/courses/detail.html
{% extends 'base.html' %}

{% block title %}Detail of {{ course.course_name }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-4"></div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <a href="{%  url 'courses:update' course.pk %}">{{ course.course_name }}</a>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ course.duration }}</li>
                    <li class="list-group-item">{{ course.description }}</li>
                    <li class="list-group-item">{{ course.price }}</li>
                </ul>
                <a class="btn btn-outline-primary mt-3" href="{%  url 'courses:list' %}">Back to list</a>
            </div>
        </div>
        <div class="col-4"></div>
    </div>
{% endblock %}

courses/templates/courses/list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}List of courses{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Search course
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="col">
                            <form method="get">
                                {{ object_list.form|crispy }}
                                <input class="btn btn-outline-primary mt-3" type="submit" value="Submit">
                            </form>
                        </div>
                        <div class="col-6"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <table class="table table-striped table-hover">
            <thead>
            <tr align="center">
                <th>No.</th>
                <th>Course name</th>
                <th>Group</th>
                <th>Duration</th>
                {% if user.is_authenticated %}
                    <th><i class="bi bi-pencil-fill"></i></th>
                    <th><i class="bi bi-trash-fill"></i></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for course in object_list.qs %}
                <tr align="center">
                    <td>{{ forloop.counter }}</td>
                    <td>
                        {% if user.is_authenticated %}
                            <a href="{% url 'courses:detail' course.pk %}">{{ course.course_name }}</a>
                        {% else %}
                            {{ course.course_name }}
                        {% endif %}
                    </td>
                    <td>
                        {% if course.group %}
                            {{ course.group.group_name }}
                        {% endif %}
                    </td>
                    <td>{{ course.duration }}</td>
                    {% if user.is_authenticated %}
                        <td><a class="btn btn-outline-primary btn-sm"
                               href="{% url 'courses:update' course.pk %}">Edit</a></td>
                        <td><a class="btn btn-outline-danger btn-sm"
                               href="{% url 'courses:delete' course.pk %}">Delete</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

courses/templates/courses/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update course{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-outline-success mt-3 btn-sm" type="submit" value="Update">
                    <a class="btn btn-outline-danger mt-3 btn-sm" href="{% url 'courses:list' %}">Cancel</a>
                </form>
            </div>
        <div class="col-3"></div>
    </div>
{% endblock %}